# Generated by Django 4.1.1 on 2022-09-10 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curd", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="created_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
